#ifndef LIBAFL_IJON_H
#define LIBAFL_IJON_H

#define IJON_FAKESYS_NR 0xa2a5

enum {
    IJON_ACTION_MAX,
    IJON_ACTION_MIN,
    IJON_ACTION_SET,
    IJON_ACTION_INC,
    IJON_ACTION_XOR_STATE,
    IJON_ACTION_RESET_STATE,
    IJON_ACTION_MAX_UNTIL,
    IJON_ACTION_CMP,
};

#endif
