all:
	@echo trying to use GNU make...
	@gmake all || echo please install GNUmake

32:
	@echo trying to use GNU make...
	@gmake 32 || echo please install GNUmake

clean:
	@gmake clean

frida_js_entry:
	@gmake frida_js_entry

frida_js_replace:
	@gmake frida_js_replace

frida_js_patch:
	@gmake frida_js_patch

frida_js_stalker:
	@gmake frida_js_stalker

debug:
	@gmake debug
