#!/usr/bin/env make
# SPDX-License-Identifier: Apache-2.0
# Copyright 2021 Ricerca Security, Inc. All rights reserved.

all:
	@echo trying to use GNU make...
	@gmake all || echo please install GNUmake

build:
	@echo trying to use GNU make...
	@gmake build || echo please install GNUmake

debug:
	@echo trying to use GNU make...
	@gmake debug || echo please install GNUmake

clean:
	@echo trying to use GNU make...
	@gmake clean || echo please install GNUmake

.PHONY: all build debug clean
