all:
	@echo trying to use GNU make...
	@gmake -j1 all || echo please install GNUmake

32:
	@echo trying to use GNU make...
	@gmake -j1 32 || echo please install GNUmake

clean:
	@gmake clean

format:
	@gmake format

hook:
	@gmake hook
