#!/bin/bash
export PWD=$(pwd)
export PARENT=$(realpath $PWD/..)
export TEST_BIN=$PWD/build/test/pngtest
export TEST_DATA_DIR=$PWD/build/test/libpng-1.2.56/contrib/pngsuite/
export QEMU_OUT=$PWD/qemu_out
export TESTINSTR_BASE_QEMU=0x4000000000
export AFL_QEMU_PERSISTENT_HOOK=$PARENT/utils/aflpp_driver/aflpp_qemu_driver_hook.so
export AFLPP_DRIVER_DUMMY_INPUT=$PWD/build/dummy.dat

export AFL_QEMU_PERSISTENT_ADDR=$($PWD/test/get_symbol_addr.py -f $TEST_BIN -s LLVMFuzzerTestOneInput -b $TESTINSTR_BASE_QEMU)
export AFL_QEMU_INST_RANGES=$($PWD/test/get_section_addrs.py -f $TEST_BIN -s .text -b $TESTINSTR_BASE_QEMU)
export AFL_QEMU_PERSISTENT_GPR=1

echo AFL_QEMU_PERSISTENT_ADDR = $AFL_QEMU_PERSISTENT_ADDR
echo AFL_QEMU_INST_RANGES = $AFL_QEMU_INST_RANGES
echo AFL_QEMU_PERSISTENT_HOOK = $AFL_QEMU_PERSISTENT_HOOK
echo AFLPP_DRIVER_DUMMY_INPUT = $AFLPP_DRIVER_DUMMY_INPUT

rm -rf $QEMU_OUT

tmux new-window -n:master  "AFL_QEMU_PERSISTENT_HOOK=$AFL_QEMU_PERSISTENT_HOOK AFL_QEMU_PERSISTENT_ADDR=$AFL_QEMU_PERSISTENT_ADDR AFL_QEMU_INST_RANGES=$AFL_QEMU_INST_RANGES AFL_QEMU_PERSISTENT_GPR=1 $PARENT/afl-fuzz -V60 -Q -i $TEST_DATA_DIR -o $QEMU_OUT -D master  -- $TEST_BIN $AFLPP_DRIVER_DUMMY_INPUT"
tmux new-window -n:slave01 "AFL_QEMU_PERSISTENT_HOOK=$AFL_QEMU_PERSISTENT_HOOK AFL_QEMU_PERSISTENT_ADDR=$AFL_QEMU_PERSISTENT_ADDR AFL_QEMU_INST_RANGES=$AFL_QEMU_INST_RANGES AFL_QEMU_PERSISTENT_GPR=1 $PARENT/afl-fuzz -V60 -Q -i $TEST_DATA_DIR -o $QEMU_OUT -S slave01 -- $TEST_BIN $AFLPP_DRIVER_DUMMY_INPUT"
tmux new-window -n:slave02 "AFL_QEMU_PERSISTENT_HOOK=$AFL_QEMU_PERSISTENT_HOOK AFL_QEMU_PERSISTENT_ADDR=$AFL_QEMU_PERSISTENT_ADDR AFL_QEMU_INST_RANGES=$AFL_QEMU_INST_RANGES AFL_QEMU_PERSISTENT_GPR=1 $PARENT/afl-fuzz -V60 -Q -i $TEST_DATA_DIR -o $QEMU_OUT -S slave02 -- $TEST_BIN $AFLPP_DRIVER_DUMMY_INPUT"
tmux new-window -n:slave03 "AFL_QEMU_PERSISTENT_HOOK=$AFL_QEMU_PERSISTENT_HOOK AFL_QEMU_PERSISTENT_ADDR=$AFL_QEMU_PERSISTENT_ADDR AFL_QEMU_INST_RANGES=$AFL_QEMU_INST_RANGES AFL_QEMU_PERSISTENT_GPR=1 $PARENT/afl-fuzz -V60 -Q -i $TEST_DATA_DIR -o $QEMU_OUT -S slave03 -- $TEST_BIN $AFLPP_DRIVER_DUMMY_INPUT"
tmux new-window -n:slave04 "AFL_QEMU_PERSISTENT_HOOK=$AFL_QEMU_PERSISTENT_HOOK AFL_QEMU_PERSISTENT_ADDR=$AFL_QEMU_PERSISTENT_ADDR AFL_QEMU_INST_RANGES=$AFL_QEMU_INST_RANGES AFL_QEMU_PERSISTENT_GPR=1 $PARENT/afl-fuzz -V60 -Q -i $TEST_DATA_DIR -o $QEMU_OUT -S slave04 -- $TEST_BIN $AFLPP_DRIVER_DUMMY_INPUT"
tmux new-window -n:slave05 "AFL_QEMU_PERSISTENT_HOOK=$AFL_QEMU_PERSISTENT_HOOK AFL_QEMU_PERSISTENT_ADDR=$AFL_QEMU_PERSISTENT_ADDR AFL_QEMU_INST_RANGES=$AFL_QEMU_INST_RANGES AFL_QEMU_PERSISTENT_GPR=1 $PARENT/afl-fuzz -V60 -Q -i $TEST_DATA_DIR -o $QEMU_OUT -S slave05 -- $TEST_BIN $AFLPP_DRIVER_DUMMY_INPUT"
tmux new-window -n:slave06 "AFL_QEMU_PERSISTENT_HOOK=$AFL_QEMU_PERSISTENT_HOOK AFL_QEMU_PERSISTENT_ADDR=$AFL_QEMU_PERSISTENT_ADDR AFL_QEMU_INST_RANGES=$AFL_QEMU_INST_RANGES AFL_QEMU_PERSISTENT_GPR=1 $PARENT/afl-fuzz -V60 -Q -i $TEST_DATA_DIR -o $QEMU_OUT -S slave06 -- $TEST_BIN $AFLPP_DRIVER_DUMMY_INPUT"
tmux new-window -n:slave07 "AFL_QEMU_PERSISTENT_HOOK=$AFL_QEMU_PERSISTENT_HOOK AFL_QEMU_PERSISTENT_ADDR=$AFL_QEMU_PERSISTENT_ADDR AFL_QEMU_INST_RANGES=$AFL_QEMU_INST_RANGES AFL_QEMU_PERSISTENT_GPR=1 $PARENT/afl-fuzz -V60 -Q -i $TEST_DATA_DIR -o $QEMU_OUT -S slave07 -- $TEST_BIN $AFLPP_DRIVER_DUMMY_INPUT"
tmux new-window -n:slave08 "AFL_QEMU_PERSISTENT_HOOK=$AFL_QEMU_PERSISTENT_HOOK AFL_QEMU_PERSISTENT_ADDR=$AFL_QEMU_PERSISTENT_ADDR AFL_QEMU_INST_RANGES=$AFL_QEMU_INST_RANGES AFL_QEMU_PERSISTENT_GPR=1 $PARENT/afl-fuzz -V60 -Q -i $TEST_DATA_DIR -o $QEMU_OUT -S slave08 -- $TEST_BIN $AFLPP_DRIVER_DUMMY_INPUT"
tmux new-window -n:slave09 "AFL_QEMU_PERSISTENT_HOOK=$AFL_QEMU_PERSISTENT_HOOK AFL_QEMU_PERSISTENT_ADDR=$AFL_QEMU_PERSISTENT_ADDR AFL_QEMU_INST_RANGES=$AFL_QEMU_INST_RANGES AFL_QEMU_PERSISTENT_GPR=1 $PARENT/afl-fuzz -V60 -Q -i $TEST_DATA_DIR -o $QEMU_OUT -S slave09 -- $TEST_BIN $AFLPP_DRIVER_DUMMY_INPUT"
tmux new-window -n:slave10 "AFL_QEMU_PERSISTENT_HOOK=$AFL_QEMU_PERSISTENT_HOOK AFL_QEMU_PERSISTENT_ADDR=$AFL_QEMU_PERSISTENT_ADDR AFL_QEMU_INST_RANGES=$AFL_QEMU_INST_RANGES AFL_QEMU_PERSISTENT_GPR=1 $PARENT/afl-fuzz -V60 -Q -i $TEST_DATA_DIR -o $QEMU_OUT -S slave10 -- $TEST_BIN $AFLPP_DRIVER_DUMMY_INPUT"
tmux new-window -n:slave11 "AFL_QEMU_PERSISTENT_HOOK=$AFL_QEMU_PERSISTENT_HOOK AFL_QEMU_PERSISTENT_ADDR=$AFL_QEMU_PERSISTENT_ADDR AFL_QEMU_INST_RANGES=$AFL_QEMU_INST_RANGES AFL_QEMU_PERSISTENT_GPR=1 $PARENT/afl-fuzz -V60 -Q -i $TEST_DATA_DIR -o $QEMU_OUT -S slave11 -- $TEST_BIN $AFLPP_DRIVER_DUMMY_INPUT"
tmux new-window -n:slave12 "AFL_QEMU_PERSISTENT_HOOK=$AFL_QEMU_PERSISTENT_HOOK AFL_QEMU_PERSISTENT_ADDR=$AFL_QEMU_PERSISTENT_ADDR AFL_QEMU_INST_RANGES=$AFL_QEMU_INST_RANGES AFL_QEMU_PERSISTENT_GPR=1 $PARENT/afl-fuzz -V60 -Q -i $TEST_DATA_DIR -o $QEMU_OUT -S slave12 -- $TEST_BIN $AFLPP_DRIVER_DUMMY_INPUT"
tmux new-window -n:slave13 "AFL_QEMU_PERSISTENT_HOOK=$AFL_QEMU_PERSISTENT_HOOK AFL_QEMU_PERSISTENT_ADDR=$AFL_QEMU_PERSISTENT_ADDR AFL_QEMU_INST_RANGES=$AFL_QEMU_INST_RANGES AFL_QEMU_PERSISTENT_GPR=1 $PARENT/afl-fuzz -V60 -Q -i $TEST_DATA_DIR -o $QEMU_OUT -S slave13 -- $TEST_BIN $AFLPP_DRIVER_DUMMY_INPUT"
tmux new-window -n:slave14 "AFL_QEMU_PERSISTENT_HOOK=$AFL_QEMU_PERSISTENT_HOOK AFL_QEMU_PERSISTENT_ADDR=$AFL_QEMU_PERSISTENT_ADDR AFL_QEMU_INST_RANGES=$AFL_QEMU_INST_RANGES AFL_QEMU_PERSISTENT_GPR=1 $PARENT/afl-fuzz -V60 -Q -i $TEST_DATA_DIR -o $QEMU_OUT -S slave14 -- $TEST_BIN $AFLPP_DRIVER_DUMMY_INPUT"
tmux new-window -n:slave15 "AFL_QEMU_PERSISTENT_HOOK=$AFL_QEMU_PERSISTENT_HOOK AFL_QEMU_PERSISTENT_ADDR=$AFL_QEMU_PERSISTENT_ADDR AFL_QEMU_INST_RANGES=$AFL_QEMU_INST_RANGES AFL_QEMU_PERSISTENT_GPR=1 $PARENT/afl-fuzz -V60 -Q -i $TEST_DATA_DIR -o $QEMU_OUT -S slave15 -- $TEST_BIN $AFLPP_DRIVER_DUMMY_INPUT"