all:
	@echo trying to use GNU make...
	@gmake all || echo please install GNUmake

32:
	@echo trying to use GNU make...
	@gmake 32 || echo please install GNUmake

clean:
	@gmake clean

qemu:
	@gmake qemu

qemu_entry:
	@gmake qemu_entry

frida:
	@gmake frida

frida_entry:
	@gmake frida_entry

debug:
	@gmake debug
