all:
	@echo trying to use GNU make...
	@gmake all || echo please install GNUmake

32:
	@echo trying to use GNU make...
	@gmake 32 || echo please install GNUmake

hook:
	@gmake hook

clean:
	@gmake clean

qemu_persistent_hook:
	@gmake qemu_persistent_hook

qemu_persistent:
	@gmake qemu_persistent

qemu:
	@gmake qemu

frida_persistent_hook:
	@gmake frida_persistent_hook

frida_persistent:
	@gmake frida_persistent

frida:
	@gmake frida

debug:
	@gmake debug

