[package]
name = "libafl_base"
version = "0.1.1"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libafl = { version = "0.15.4", features = ["prelude"] }
libafl_bolts = { version = "0.15.4" }
custom_mutator = { path = "../rust/custom_mutator", features = ["afl_internals"] }
serde = { version = "1.0", default-features = false, features = ["alloc"] } # serialization lib

[lib]
crate-type = ["cdylib"]
