all:
	@echo trying to use GNU make...
	@gmake all || echo please install GNUmake

32:
	@echo trying to use GNU make...
	@gmake 32 || echo please install GNUmake

clean:
	@gmake clean

frida-noasan:
	@gmake frida-noasan

frida:
	@gmake frida

debug:
	@gmake debug

run:
	@gmake run
