/*
   american fuzzy lop++ - wrapper for GNU ld
   -----------------------------------------

   Originally written by Michal Zalewski

   Now maintained by by Marc Heuse <mh@mh-sec.de>,
                        Heiko Eißfeldt <heiko.eissfeldt@hexco.de> and
                        Andrea Fioraldi <andreafioraldi@gmail.com>

   Copyright 2016, 2017 Google Inc. All rights reserved.
   Copyright 2019-2020 AFLplusplus Project. All rights reserved.

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at:

     http://www.apache.org/licenses/LICENSE-2.0

   The sole purpose of this wrapper is to preprocess clang LTO files before
   linking by ld and perform the instrumentation on the whole program.

 */

#define AFL_MAIN

#include "config.h"
#include "types.h"
#include "debug.h"
#include "alloc-inl.h"

#include <stdio.h>
#include <unistd.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <ctype.h>
#include <fcntl.h>

#include <sys/wait.h>
#include <sys/time.h>

static u8** ld_params;              /* Parameters passed to the real 'ld'   */

static u8* input_file;              /* Originally specified input file      */
static u8* modified_file;           /* Instrumented file for the real 'ld'  */

static u8 be_quiet,                 /* Quiet mode (no stderr output)        */
    clang_mode,                     /* Running in clang mode?               */
    pass_thru,                      /* Just pass data through?              */
    just_version;                   /* Just show version?                   */

static u32 inst_ratio = 100,        /* Instrumentation probability (%)      */
    ld_par_cnt = 1;                 /* Number of params to 'ld'             */

/* If we don't find --32 or --64 in the command line, default to
   instrumentation for whichever mode we were compiled with. This is not
   perfect, but should do the trick for almost all use cases. */

#ifdef WORD_SIZE_64

static u8 use_64bit = 1;

#else

static u8 use_64bit = 0;

#ifdef __APPLE__
#error "Sorry, 32-bit Apple platforms are not supported."
#endif                                                         /* __APPLE__ */

#endif                                                     /* ^WORD_SIZE_64 */

/* Examine and modify parameters to pass to 'ld'. Note that the file name
   is always the last parameter passed by GCC, so we exploit this property
   to keep the code simple. */

static void edit_params(int argc, char** argv) {

  u8 *tmp_dir = getenv("TMPDIR"), *afl_ld = getenv("AFL_LD");
  u32 i;

#ifdef __APPLE__

  u8 use_clang_ld = 0;

  /* On MacOS X, the Xcode cctool 'ld' driver is a bit stale and does not work
     with the code generated by newer versions of clang that are hand-built
     by the user. See the thread here: http://goo.gl/HBWDtn.

     To work around this, when using clang and running without AFL_AS
     specified, we will actually call 'clang -c' instead of 'ld -q' to
     compile the assembly file.

     The tools aren't cmdline-compatible, but at least for now, we can
     seemingly get away with this by making only very minor tweaks. Thanks
     to Nico Weber for the idea. */

  if (clang_mode && !afl_ld) {

    use_clang_ld = 1;

    afl_ld = getenv("AFL_CC");
    if (!afl_ld) afl_ld = getenv("AFL_CXX");
    if (!afl_ld) afl_ld = "clang";

  }

#endif                                                         /* __APPLE__ */

  /* Although this is not documented, GCC also uses TEMP and TMP when TMPDIR
     is not set. We need to check these non-standard variables to properly
     handle the pass_thru logic later on. */

  if (!tmp_dir) tmp_dir = getenv("TEMP");
  if (!tmp_dir) tmp_dir = getenv("TMP");
  if (!tmp_dir) tmp_dir = "/tmp";

  ld_params = ck_alloc((argc + 32) * sizeof(u8*));

  ld_params[0] = afl_ld ? afl_ld : (u8*)"ld";

  ld_params[argc] = 0;

  for (i = 1; i < argc - 1; i++) {

    if (!strcmp(argv[i], "--64"))
      use_64bit = 1;
    else if (!strcmp(argv[i], "--32"))
      use_64bit = 0;

#ifdef __APPLE__

    /* The Apple case is a bit different... */

    if (!strcmp(argv[i], "-arch") && i + 1 < argc) {

      if (!strcmp(argv[i + 1], "x86_64"))
        use_64bit = 1;
      else if (!strcmp(argv[i + 1], "i386"))
        FATAL("Sorry, 32-bit Apple platforms are not supported.");

    }

    /* Strip options that set the preference for a particular upstream
       assembler in Xcode. */

    if (clang_mode && (!strcmp(argv[i], "-q") || !strcmp(argv[i], "-Q")))
      continue;

#endif                                                         /* __APPLE__ */

    ld_params[ld_par_cnt++] = argv[i];

  }

#ifdef __APPLE__

  /* When calling clang as the upstream assembler, append -c -x assembler
     and hope for the best. */

  if (use_clang_ld) {

    ld_params[ld_par_cnt++] = "-c";
    ld_params[ld_par_cnt++] = "-x";
    ld_params[ld_par_cnt++] = "assembler";

  }

#endif                                                         /* __APPLE__ */

  input_file = argv[argc - 1];

  if (input_file[0] == '-') {

    if (!strcmp(input_file + 1, "-version")) {

      just_version = 1;
      modified_file = input_file;
      goto wrap_things_up;

    }

    if (input_file[1])
      FATAL("Incorrect use (not called through afl-gcc?)");
    else
      input_file = NULL;

  } else {

    /* Check if this looks like a standard invocation as a part of an attempt
       to compile a program, rather than using gcc on an ad-hoc .s file in
       a format we may not understand. This works around an issue compiling
       NSS. */

    if (strncmp(input_file, tmp_dir, strlen(tmp_dir)) &&
        strncmp(input_file, "/var/tmp/", 9) &&
        strncmp(input_file, "/tmp/", 5) &&
        getenv("AFL_AS_FORCE_INSTRUMENT") == NULL)
      pass_thru = 1;
    else if (getenv("AFL_AS_FORCE_INSTRUMENT"))
      unsetenv("AFL_AS_FORCE_INSTRUMENT");

  }

  modified_file =
      alloc_printf("%s/.afl-%u-%u.s", tmp_dir, getpid(), (u32)time(NULL));

wrap_things_up:

  ld_params[ld_par_cnt++] = modified_file;
  ld_params[ld_par_cnt] = NULL;

}

/* Process input file, generate modified_file. Insert instrumentation in all
   the appropriate places. */

static void add_instrumentation(void) {

  // TODO

}

/* Main entry point */

int main(int argc, char** argv) {

  s32 pid;
  u32 rand_seed;
  int status;
  u8* inst_ratio_str = getenv("AFL_INST_RATIO");

  struct timeval  tv;
  struct timezone tz;

  clang_mode = !!getenv(CLANG_ENV_VAR);

  if (!getenv("AFL_QUIET")) {

    SAYF(cCYA "afl-ld" VERSION cRST
              " by Marc \"vanHauser\" Heuse <mh@mh-sec.de>\n");

  } else

    be_quiet = 1;

  if (argc < 2) {

    SAYF(
        "\n"
        "This is a helper application for afl-fuzz. It is a wrapper around GNU "
        "'ld',\n"
        "executed by the toolchain whenever using afl-gcc or afl-clang. You "
        "probably\n"
        "don't want to run this program directly.\n\n"

        "Rarely, when dealing with extremely complex projects, it may be "
        "advisable to\n"
        "set AFL_INST_RATIO to a value less than 100 in order to reduce the "
        "odds of\n"
        "instrumenting every discovered branch.\n\n");

    exit(1);

  }

  if (getenv("AFL_LD") == NULL) {

    execvp("/bin/ld", argv);  // <= TODO
    FATAL("Oops, failed to execute '%s' - check your PATH", "/bin/ld");

  }

  gettimeofday(&tv, &tz);

  rand_seed = tv.tv_sec ^ tv.tv_usec ^ getpid();

  srandom(rand_seed);

  edit_params(argc, argv);

  if (inst_ratio_str) {

    if (sscanf(inst_ratio_str, "%u", &inst_ratio) != 1 || inst_ratio > 100)
      FATAL("Bad value of AFL_INST_RATIO (must be between 0 and 100)");

  }

  if (getenv(AS_LOOP_ENV_VAR))
    FATAL("Endless loop when calling 'ld' (remove '.' from your PATH)");

  setenv(AS_LOOP_ENV_VAR, "1", 1);

  if (!just_version) add_instrumentation();

  if (!(pid = fork())) {

    execvp(ld_params[0], (char**)ld_params);
    FATAL("Oops, failed to execute '%s' - check your PATH", ld_params[0]);

  }

  if (pid < 0) PFATAL("fork() failed");

  if (waitpid(pid, &status, 0) <= 0) PFATAL("waitpid() failed");

  if (!getenv("AFL_KEEP_ASSEMBLY")) unlink(modified_file);

  exit(WEXITSTATUS(status));

}

