{
 "title": "Fuzzing",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Exec/s",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "fuzzing{type=\"execs_per_sec\"}"
    }
   ]
  },
  {
   "title": "Total Crashes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "fuzzing{type=\"total_crashes\"}"
    }
   ]
  },
  {
   "title": "Var Byte Count",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "fuzzing{type=\"var_byte_count\"}"
    }
   ]
  },
  {
   "title": "Unique Crashes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "fuzzing{type=\"unique_crashes\"}"
    }
   ]
  },
  {
   "title": "Unique Hangs",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "fuzzing{type=\"unique_hangs\"}"
    }
   ]
  },
  {
   "title": "Slowest Exec Ms",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "fuzzing{type=\"slowest_exec_ms\"}"
    }
   ]
  },
  {
   "title": "Cycles dones",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "fuzzing{type=\"cycle_done\"}"
    }
   ]
  },
  {
   "title": "Total Execs",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "fuzzing{type=\"execs_done\"}"
    }
   ]
  },
  {
   "title": "Current fuzz item",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "fuzzing{type=\"cur_item\"}"
    }
   ]
  },
  {
   "title": "Cycles done without find",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "fuzzing{type=\"cycles_wo_finds\"}"
    }
   ]
  },
  {
   "title": "Corpus Favored",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "fuzzing{type=\"corpus_favored\"}"
    }
   ]
  },
  {
   "title": "Havoc Expansion",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "fuzzing{type=\"havoc_expansion\"}"
    }
   ]
  },
  {
   "title": "Edges Found",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "fuzzing{type=\"edges_found\"}"
    }
   ]
  },
  {
   "title": "Corpus Imported",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "fuzzing{type=\"corpus_imported\"}"
    }
   ]
  },
  {
   "title": "Pending Total",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "fuzzing{type=\"pending_total\"}"
    }
   ]
  },
  {
   "title": "Pending favs",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "fuzzing{type=\"pending_favs\"}"
    }
   ]
  },
  {
   "title": "Max Depth",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "fuzzing{type=\"max_depth\"}"
    }
   ]
  }
 ]
}